##Bins
#E_nu_bins: "np.logspace(1,7,12+1)"
E_nu_bins: "np.concatenate((np.logspace(1,2,1),np.logspace(2,6,8+1)))"
nu_bin_centers: "np.sqrt(E_nu_bins[:-1] * E_nu_bins[1:])"

#E_mu_bins: "np.logspace(1,7,12+1)"
E_mu_bins: "((np.logspace(1,6,8+1)))"
mu_bin_centers: "np.sqrt(E_mu_bins[:-1] * E_mu_bins[1:])"

gridpts_mu: "((np.logspace(1,6,8+1)))"
gridpts_nu: "np.concatenate((np.logspace(1,2,1),np.logspace(2,6,8+1)))"

flavours: ['NuE','NuMu']
angles: "np.linspace(0,1.0,6)"
depths: "np.concatenate([np.linspace(1.40,2.0,2),np.linspace(2.1,2.5,2)])"

mult_bins: "np.linspace(0,5,5+1)"
##Filepaths
corsika_sample: '/data/user/zrechav/airshowered_corsika/22803/merge_test/merge_test.hdf5'
gcd: '/cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2020.Run134142.Pass2_V0.i3.gz'


flavour_mask_NuE_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/Flavour_mask_NuE.npy'
flavour_mask_NuMu_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/Flavour_mask_NuMu.npy'
flavour_mask_NuTau_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/Flavour_mask_NuTau.npy'
single_muon_mask_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/SingleMuonMask.npy'
double_muon_mask_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/DoubleMuonMask.npy'
triple_muon_mask_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/TripleMuonMask.npy'
quad_muon_mask_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/QuadrupleMuonMask.npy'

angle_masks_base_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/Angle_mask_'
depth_masks_base_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/Depth_mask_'
flavour_masks_base_path: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/masked_pickles/Flavour_mask_'

#histogram output directories
single_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/histograming/1D/'
double_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/histograming/2D/'
triple_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/histograming/3D/'
quad_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/histograming/4D/'

#spline output directories
single_splines_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/splining/1D/'
double_splines_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/splining/2D/'
triple_splines_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/splining/3D/'

##multiplicity output directories
multi_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/multiplicity_mapping/'

#normalized histogram output directories
norm_single_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/normalized/histograming/1D/'
norm_double_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/normalized/histograming/2D/'
norm_triple_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/normalized/histograming/3D/'
norm_quad_hists_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/normalized/histograming/4D/'

#normalized spline output directories
norm_single_splines_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/normalized/splining/1D/'
norm_double_splines_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/normalized/splining/2D/'
norm_triple_splines_base: '/data/user/zrechav/output_SelfVeto_Correlation_Tables/normalized/splining/3D/'



