##Bins
E_nu_bins: "np.logspace(1,7,12+1)"
nu_bin_centers: "np.sqrt(E_nu_bins[:-1] * E_nu_bins[1:])"

E_mu_bins: "np.logspace(1,7,12+1)"
mu_bin_centers: "np.sqrt(E_mu_bins[:-1] * E_mu_bins[1:])"

gridpts_mu: "np.logspace(1,7,18+1)"
gridpts_nu: "np.logspace(1,7,18+1)"

flavours: ['NuE','NuMu']
angles: "np.linspace(0,1.0,6)"
depths: "np.concatenate([np.linspace(1.40,2.0,2),np.linspace(2.1,2.5,2)])"

mult_bins: "np.linspace(0,100,100+1)"
##Filepaths
corsika_sample: '/data/user/zrechav/compiled_hdf5s/airshowered_corsika/Corsika_20904_new_0000-0999.hdf5'
gcd: '/cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz'


flavour_mask_NuE_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/Flavour_mask_NuE.npy'
flavour_mask_NuMu_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/Flavour_mask_NuMu.npy'
flavour_mask_NuTau_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/Flavour_mask_NuTau.npy'
single_muon_mask_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/SingleMuonMask.npy'
double_muon_mask_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/DoubleMuonMask.npy'
triple_muon_mask_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/TripleMuonMask.npy'
quad_muon_mask_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/QuadrupleMuonMask.npy'

angle_masks_base_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/Angle_mask_'
depth_masks_base_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/Depth_mask_'
flavour_masks_base_path: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/picklemaking/masked_pickles/Flavour_mask_'

#histogram output directories
single_hists_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/histograming/histograms/1D/'
double_hists_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/histograming/histograms/2D/'
triple_hists_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/histograming/histograms/3D/'
quad_hists_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/histograming/histograms/4D/'

#spline output directories
single_splines_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/splining/splines/1D/'
double_splines_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/splining/splines/2D/'
triple_splines_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/splining/splines/3D/'

##multiplicity output directories
multi_base: '/home/zrechav/SelfVeto_Correlation_Tables/scripts/multiplicity_mapping/multiplicites/'



