# Muon resimulation
# vcut altered

chain_name: muon_resimulation
seed: 1337

# Number of the dataset
dataset_number: 100
# Events generated for each file
n_events_per_run: 1000
# Number of total runs/file
n_runs: 1000

# used icemodel
icemodel: SpiceLea
# For default location: leave empty
icemodel_location:

# Muon Generation specific settings
# Starting Energy GeV
e_min: !!float 1e4
# Maximal Energy GeV
e_max: !!float 1e4
# Starting zenith
zenith_min: 0.
# End zenith
zenith_max: 180.
# Starting azimuth
azimuth_min: 0.
# End azimuth
azimuth_max: 360.
# Create vertex on convex hull
use_convex_hull: True
# Distance to move vertex further past 
# the convex hull [in meter]
extend_past_hull: 60.

# MuonPropagation specific options
muon_propagation_config : {
    media_definition: /data/user/mhuennefeld/data/simulation/v_cuts/mediadef_vcut_high
}

# Whether I3MCPE list should be stored
clsim_keep_mcpe: False

# Detector Simulation
# keep MCPEs in frame
det_keep_mc_hits: True
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: False
# Keep everything upto run X
det_pass2_keep_all_upto: -1
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True

