chain_name: double_pulse_resimulations
seed: 1337
dataset_number: 13337
gcd_2012: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2012.56063_V1.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2015.57161_V0.i3.gz
n_events_per_run: 100
n_runs: 1000
skymap_path: '/data/user/mmeier/resimulation/data/skymap.npz'
xsec_table_path: '/data/user/mmeier/resimulation/data/dsigmady_nu_CC_iso_NLO_HERAPDF15NLO_EIG.dat'
smearing_angle: 5.
icemodel: SpiceLea
clsim_unshadowed_fraction: 0.99
clsim_ignore_muon_light: False
clsim_usegpus: True
clsim_keep_mcpe: False
clsim_dom_oversize: 1.
clsim_hybrid_mode: False
particle_type: numu
