# Number of the dataset
dataset_number: 20000
# Events generated for each file
n_events_per_run: 1000
# Number of total runs/file
n_runs: 1000

# Pattern for the outputfile
output_pattern: '{run_folder}/Level0.{step}_cascade_ppc_IC86.2012_pass2.{dataset_number:6d}.{run_number}.i3.bz2'
# sub-dict to indicate need resources
resources:
  # Indication which steps need GPUs, default is 0
  gpus:
    1: 1
  # Indication of needed memory for each step if nothing is set 1GB is assumed as default
  memory:
    1: 3gb
    2: 2gb
    3: 2gb
    13: 2gb
    23: 2gb
    33: 2gb
  # Indication of the walltime (in hours) for each step, if nothing is set the system default for dagman and 1h for pbs are assumed
  walltime:
  # Indication of the number of cores for each step, default is 1
  cpus:
    1: 1

# Dagman options
dagman_max_jobs: 5000
dagman_submits_interval: 500
dagman_scan_interval: 1
dagman_submit_delay: 0


# Options used in the steps
# Options that are expected to be set to generate the scripts
seed: 1337
# Whether file after IceTray should be kept
keep_crashed_files: 0
# If True: use I3GSLRandomService, otherwise use I3SPRNGRandomService
# (Newer cmvfs python and icecube builds do not have I3SPRNGRandomService)
random_service_use_gslrng: True

# PATH to the GCD File
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz

# -------------------------
# Step 0: Neutrino Injection
# -------------------------
# Neutrino Generation specific settings
# Energy range for primary particle
primary_energy_range: [!!float 1e2, !!float 1e8]
# Fraction of primary energy in hadrons
fractional_energy_in_hadrons_range: [0.0001, 0.0001]
# Zenith range of primary and cascade in degrees
zenith_range: [0., 180.]
# Azimuth range of primary and cascade in degrees
azimuth_range: [0., 360.]
# vertex time range in ns [min,max]
time_range: [0,0]
# vertex range in m [min,max]
x_range: [-900,900]
y_range: [-900,900]
z_range: [-800,800]
# Shift sampled vertex back along track to this distance to convex hull
# Leave empts if no shifting is desired
shift_vertex_distance:
# Maximum Distance of vertex to convex hull around IceCube
# Leave empty if no limit is desired.
max_vertex_distance: 300
# Maximum Distance of track to convex hull around IceCube
# Leave empty if no limit is desired.
max_track_distance:
# The convex hull to use if required ['IceCube' or 'DeepCore']
convex_hull_distance_function: 'IceCube'
# flavors. Options are: 'NuE', 'NuMu', 'NuTau'
flavors: ['NuE']
# interaction types. Options are: 'CC', 'NC'
interaction_types: ['CC']
# keys to keep constant per run [Leave empty for none]
constant_vars:
# oversampling to use
oversampling_factor:
# oversample after proposal or before?
oversample_after_proposal: False
# keep keys for merging of oversampled events
oversampling_keep_keys: []

# Distance splits are not available for snowstorm chain
distance_splits:
threshold_doms:
oversize_factors:

# -----------------------
# Step 1: PPC Propagation
# -----------------------

# PPC Configuration
ppc_config:
  environment_variables:
        PPCTABLESDIR: "$I3_BUILD/ice-models/resources/models/spice_bfr-dv1_complete"

  arguments:
        MCTree: 'I3MCTree'

# -----------------------------
# Step 2: Detector Simulation
# -----------------------------
# Remove this list of keys from the M-Frames
det_remove_keys_from_m_frame: []
# keep MCPEs in frame
det_keep_mc_hits: False
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: False
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True
# Keep everything upto run X
det_keep_all_upto: -1
# add beacon lauches.
det_add_beacon_launches: True
# reduce peak memory use by repeatedly merging hits as they are generated.  WARNING: Use of this option may slightly reduce precision and drastically increase running time. It is potentially useful for very bright events, and probably harmful for very long events.
det_low_mem: False
# remove events that don't pass any trigger.
det_filter_trigger: True
# do not run Vuvuzela.
det_skip_noise_generation: False
# convert I3MCTree to linearized version if True
det_convert_to_linear_tree: True
# If this is a Genie simulation, then this needs to be set to True
det_is_genie_simulation: False
# If this is an IceTop simulation, then this needs to be set to True
det_is_icetop_simulation: False
# DOM Efficiency Resampling
#(If det_dom_eff_resmapling_sample_efficiency is set to 0,
# no resampling will be performed )
det_dom_eff_resmapling_sample_efficiency: 0.
det_dom_eff_resmapling_generated_efficiency: 0.


# ------------------
# Step 3: Get Pulses
# ------------------
# Simplified version of L1 processing

# Keep untriggered events substream and keys
L1_keep_untriggered: True
