# Number of the dataset
dataset_number: 100
# Events generated for each file
n_events_per_run: 1000
# Number of total runs/file
n_runs: 1000

# Pattern for the outputfile
output_pattern: '{run_folder}/Level0.{step}_cascade_simulation_IC86.2012_pass2.{dataset_number:6d}.{run_number}.i3.bz2'
# sub-dict to indicate need resources
resources:
  # Indication which steps need GPUs, default is 0
  gpus:
    1: 1
  # Indication of needed memory for each step if nothing is set 1GB is assumed as default
  memory:
    1: 6gb
    2: 5gb
    3: 3gb
    13: 3gb
    23: 3gb
    24: 3gb
    25: 3gb
    32: 3gb
    33: 3gb
    34: 3gb
    35: 3gb
  # Indication of the walltime (in hours) for each step, if nothing is set the system default for dagman and 1h for pbs are assumed
  walltime:
  # Indication of the number of cores for each step, default is 1
  cpus:

# Dagman options
dagman_max_jobs: 5000
dagman_submits_interval: 500
dagman_scan_interval: 1
dagman_submit_delay: 0



# Options used in the steps
# Options that are expected to be set to generate the scripts
seed: 1337
# Whether file after IceTray should be kept
keep_crashed_files: 0

# PATH to the GCD File
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2015.57161_V0.i3.gz
gcd_2012: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2012.56063_V1.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2015.57161_V0.i3.gz


# Cascade Generation specific settings
# Energy range for primary particle
primary_energy_range: [!!float 1e2, !!float 1e7]
# Fraction of primary energy in hadrons
fractional_energy_in_hadrons_range: [0.001, 1.0]
# Zenith range of primary and cascade in degrees
zenith_range: [0., 180.]
# Azimuth range of primary and cascade in degrees
azimuth_range: [0., 360.]
# vertex time range in ns [min,max]
time_range: [9000,12000]
# vertex range in m [min,max]
x_range: [-400,400]
y_range: [-400,400]
z_range: [-400,400]
# Maximum Distance of vertex to convex hull around IceCube
max_vertex_distance: 60
# flavors. Options are: 'NuE', 'NuMu', 'NuTau'
flavors: ['NuE']
# interaction types. Options are: 'CC', 'NC'
interaction_types: ['NC']
# oversampling to use
oversampling_factor:
# oversample after proposal or before?
oversample_after_proposal: False
# keep keys for merging of oversampled events
oversampling_keep_keys: []


# Used icemodel
icemodel: SpiceMie
# For default location: leave empty
icemodel_location:


# MuonPropagation specific options
muon_propagation_config : {}

# CLSIM specific options
# Ratio of the dom not shadowed by calbes other anything else
clsim_unshadowed_fraction: 0.99
# whether direct light of muons should be ignored
clsim_ignore_muon_light: False
# Run CLSIM using GPUS
clsim_usegpus: True
# DOM oversize factor
clsim_dom_oversize: 5.
# Whether I3MCPE list should be stored
clsim_keep_mcpe: False
# Whether CLsim should run in hybrid mode
clsim_hybrid_mode: False

# use smarter DOM oversize options?
distance_splits:
threshold_doms:
oversize_factors:





# Detector Simulation
# keep MCPEs in frame
det_keep_mc_hits: False
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: False
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True
# Keep everything upto run X
det_pass2_keep_all_upto: 1000
# add beacon lauches.
det_add_beacon_launches: True
# reduce peak memory use by repeatedly merging hits as they are generated.  WARNING: Use of this option may slightly reduce precision and drastically increase running time. It is potentially useful for very bright events, and probably harmful for very long events.
det_low_mem: False
# remove events that don't pass any trigger.
det_filter_trigger: True
# do not run Vuvuzela.
det_skip_noise_generation: False



# Filtering Settings

# Set the Min Bias prescale to something other than default
L1_min_bias_prescale: !!null
# MC is produced by DOMSimulator (default=False)
L1_2012_dom_simulator: False
# Apply QConverter, use if file is P frame only
L1_2012_qify: False
# Retrigger
L1_2012_retrigger: False
# Run GFU
L1_pass2_run_gfu: true


# 2017 Online L2 Processing

# Keep all online L2 events or just GFU?
OnlineL2_keep_all_L2: True
# Keep all time residuals per event
OnlineL2_keep_time_residuals: False


